### ISSUE TITLE
Arctic Outpost AM1270

### ISSUE THREAD

**Issue by ikester8** [archphile/WebRadios#1]
Hello, I created a file for streaming Arctic Outpost AM1270, Longyearben, Svalbard, Norway, for your approval and inclusion.
[Arctic Outpost AM1270.pls.zip](https://github.com/archphile/WebRadios/files/6057970/Arctic.Outpost.AM1270.pls.zip)

**Comment by archphile** [comment]
https://github.com/archphile/WebRadios/commit/06764ba43586afd5bc3794830733addeda120860
